Repository Systax-Technologies/backend, pull requests merged in 2022-06, with the labels that each got.

#9 Refactor database
  app/models/employee/dto/employee.input.server.ts
  app/models/employee/dto/employee.server.ts
  app/models/employee/employee.server.ts
  app/models/employee/index.server.ts
  app/models/product/dto/product.input.server.ts
  app/models/product/dto/product.server.ts
  app/models/product/index.server.ts
  app/models/product/product.server.ts
  prisma/schema.prisma
  tailwind.config.js
Labels: refactor

#52 fix(database error): fix login database error
  app/lib/authentication.server.ts
  app/models/customer/customer.server.tsx
  app/models/dto/index.ts
  app/models/employee/employee.server.tsx
  app/routes/api/ecommerce/login.ts
  app/routes/api/warehouse/login.ts
  prisma/schema.prisma
Labels: type: bug, flag: high priority

#53 Feat 51 create product api
  app/lib/parse-body.server.ts
  app/models/product/product.server.tsx
  app/routes/api/v1/warehouse/products/$productId.ts
  app/routes/api/v1/warehouse/products/index.ts
Labels: type: enhancement, flag: high priority

#56 docs(readme): update docs, move login route inside v1 folder
  README.md
  app/routes/api/v1/ecommerce/login.ts
  app/routes/api/v1/warehouse/login.ts
  app/routes/api/v1/warehouse/products/index.ts
Labels: type: documentation

#71 docs: update api docs
  README.md
Labels: type: documentation

#73 Code refactor
  app/models/activeProduct/activeProduct.server.tsx
  app/models/customer/customer.server.tsx
  app/models/dto/index.ts
  app/models/employee/employee.server.tsx
  app/models/order/order.server.tsx
  app/models/product/product.server.tsx
  app/models/productType/productType.server.tsx
  app/routes/api/v1/warehouse/employees/employee/index.ts
  app/routes/api/v1/warehouse/employees/role/$role.ts
Labels: flag: refactor, flag: high priority

#75 refactor: add helpers for http request error, refactor code accordingly
  app/helpers/app-helpers.server.ts
  app/lib/parse-body.server.ts
  app/routes/api/v1/warehouse/products/$productId.ts
  app/routes/api/v1/warehouse/products/count/by-status/$productStatus.ts
  app/routes/api/v1/warehouse/products/count/by-type/$productTypeId.ts
  app/routes/api/v1/warehouse/products/index.ts
Labels: flag: refactor

#77 refactor(database): update prisma, refactor product models
  app/models/dto/index.ts
  app/models/product/product.server.tsx
  app/models/productInstance/index.server.tsx
  app/models/productInstance/productInstance.server.tsx
  app/models/productType/index.server.tsx
  app/models/productType/productType.server.tsx
  app/routes/api/v1/warehouse/productType/$productTypeId.ts
  app/routes/api/v1/warehouse/productType/index.ts
  app/routes/api/v1/warehouse/products/$productId.ts
  app/routes/api/v1/warehouse/products/count/by-status/$productStatus.ts
  app/routes/api/v1/warehouse/products/count/by-type/$productTypeId.ts
  app/routes/api/v1/warehouse/products/index.ts
  app/routes/api/v1/warehouse/products/productActivation.ts
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: type: bug, type: dependencies, lang: typescript, flag: refactor, type: database, flag: high priority
