Repository Systax-Technologies/backend, pull requests merged in 2022-07, with the labels that each got.

#108 refactor(API): code refactor APIs
  app/models/activeProductInstance/index.server.tsx
  app/models/activeProducts/activeProducts.server.tsx
  app/models/activeProducts/index.server.tsx
  app/models/customer/customer.server.tsx
  app/models/dto/index.ts
  app/models/product/product.server.tsx
  app/routes/api/v1/warehouse/activeProducts/$activeProductInstaceId.ts
  app/routes/api/v1/warehouse/activeProducts/index.ts
  app/routes/api/v1/warehouse/customers/$customerId/activeProducts.ts
  app/routes/api/v1/warehouse/customers/$customerId/index.ts
  app/routes/api/v1/warehouse/customers/$customerId/orders.ts
  app/routes/api/v1/warehouse/customers/index.ts
  app/routes/api/v1/warehouse/employees/$employeeId/index.ts
  app/routes/api/v1/warehouse/employees/employee/index.ts
  app/routes/api/v1/warehouse/employees/index.ts
  app/routes/api/v1/warehouse/employees/login.ts
  app/routes/api/v1/warehouse/products/$productId.ts
  app/routes/api/v1/warehouse/products/index.ts
  prisma/seed.ts
Labels: flag: high priority

#110 Refactor `verifyRequest` and `findEmployees`
  app/lib/verify-request.server.ts
  app/models/dto/index.ts
  app/models/employee/employee.server.tsx
  app/routes/api/v1/ecommerce/customers/creditCard/index.ts
  app/routes/api/v1/ecommerce/customers/index.ts
  app/routes/api/v1/warehouse/activeProducts/$activeProductInstaceId.ts
  app/routes/api/v1/warehouse/activeProducts/index.ts
  app/routes/api/v1/warehouse/customers/$customerId/activeProducts.ts
  app/routes/api/v1/warehouse/customers/$customerId/index.ts
  app/routes/api/v1/warehouse/customers/$customerId/orders.ts
  app/routes/api/v1/warehouse/customers/index.ts
  app/routes/api/v1/warehouse/employees/$employeeId/index.ts
  app/routes/api/v1/warehouse/employees/index.ts
  app/routes/api/v1/warehouse/employees/me.ts
  app/routes/api/v1/warehouse/orders/$orderId.ts
  app/routes/api/v1/warehouse/orders/by-id/index.ts
  app/routes/api/v1/warehouse/orders/by-status/$status.ts
  app/routes/api/v1/warehouse/orders/dates/within-delivered/index.ts
  app/routes/api/v1/warehouse/orders/dates/within-ordered/index.ts
  app/routes/api/v1/warehouse/orders/dates/within-shipped/index.ts
  app/routes/api/v1/warehouse/orders/index.ts
  app/routes/api/v1/warehouse/productInstances/$productInstanceId.ts
  app/routes/api/v1/warehouse/productInstances/count/by-status/$productInstanceStatus.ts
  app/routes/api/v1/warehouse/productInstances/count/by-type/$productId.ts
  app/routes/api/v1/warehouse/productInstances/index.ts
  app/routes/api/v1/warehouse/productInstances/productInstanceActivation.ts
  app/routes/api/v1/warehouse/products/$productId.ts
  app/routes/api/v1/warehouse/products/index.ts
  docker-compose.yaml
Labels: flag: high priority

#119 feat(employee info): add route to retrieve employee infos via the jwt
  app/routes/api/v1/warehouse/employees/me.ts
Labels: flag: high priority

#126 Refactor
  README.md
  app/routes/api/v1/ecommerce/customers/creditCard/index.ts
  app/routes/api/v1/ecommerce/customers/index.ts
  app/routes/api/v1/ecommerce/customers/login.ts
  app/routes/api/v1/ecommerce/orders/index.ts
  app/routes/api/v1/warehouse/orders/by-id/index.ts
  app/routes/api/v1/warehouse/orders/dates/within-delivered/index.ts
  app/routes/api/v1/warehouse/orders/dates/within-ordered/index.ts
  app/routes/api/v1/warehouse/orders/dates/within-shipped/index.ts
  app/routes/api/v1/warehouse/orders/index.ts
  app/routes/api/v1/warehouse/productInstances/index.ts
Labels: flag: refactor

#127 refactor(orders): add status for cancelled order
  README.md
  app/models/order/order.server.tsx
  prisma/schema.prisma
Labels: type: database
